### PR TITLE
[23] Extend FIND_RECORDS to find by ID

### PR DESCRIPTION
**Pull request by irushavm**
## Description
Changes Made:
- Add docs on BIOMD API interface
- Add eq_id operation in FIND call where the Value will be encapsulated in the Mongo ObjectId

## Related Issue
#23 

## How Has This Been Tested?
Using API Testing Tool

### CODE REVIEW

**Comment by akshaypuli** [comment]
@irushavm  Can you move this PR to dev-v020 branch?

**Review by akshaypuli — DISMISSED** [review]
Tested using Test Case # 5. Functioning as intended

**Comment by akshaypuli** [comment]
Need to change the base branch to dev-0.2.0

**Review by akshaypuli — APPROVED** [review]

**Review by oaedward — APPROVED** [review]

**Comment by irushavm** [comment]
@akshaypuli Ah I see the error now. I have some thoughts on how this can be solved.

**Pull request merged**
